### ISSUE TITLE
V1.0.0 Add fonts to proycts and colors

### ISSUE THREAD

**Issue by martindelahorra** [martindelahorra/tedxapp#3]

**Comment by Mauffin** [comment]
add font and colors in Customization config [b209907] but didn't test the font

**Comment by Mauffin** [comment]
added fonts and tested in explorer view.

**Comment by martindelahorra** [comment]
![image](https://github.com/user-attachments/assets/fd3e8304-594c-4e8d-8240-d66f47e1457b)

**Comment by Mauffin** [comment]
![image](https://github.com/user-attachments/assets/662f8e9d-253d-4b32-84bd-248c02d9c15b)
